baseurl = "https://jkeun.github.io/"
title = "jnotes"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "ko-kr"
copyright = "Code released under the Apache 2.0 license."

[author]
  name = "Jay"

[params]
  DateForm = "Fri, Oct 13, 2016"
  Description = "Data, Learning"
  Author = "Jay"
  email = "jkeun1224@gmail.com"
  Ganalytics = "XX-00000000-0"

[[params.social]]
  title = "github"
  url = "https://github.com/jkeun"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/jaekeun.park.7"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
