baseurl = "https://jkeun.github.io/"
title = "jnotes"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "ko-kr"
copyright = "Copyright © 2016 by JKEUN All rights reserved."

[author]
  name = "Jay"

[params]
  DateForm = "Fri, Oct 13, 2016"
  Description = "Blog of Data Science, Machine learning, Deep learning, Tensorflow, Python, Web, Programming, 파이썬, 머신러닝, 데이터, 사이언스를 배우는 블로그 입니다."
  Keywords = "Data, Science, Machine, Learning, Deep, Tensorflow, Python, Web, Data Scientist, 파이썬, 머신러닝, 빅데이터, 데이터사이언스, 데이터"
  Author = "Jay"
  email = "jkeun1224@gmail.com"
  Ganalytics = "UA-85991641-1"
  

[[params.social]]
  title = "github"
  url = "https://github.com/jkeun"
[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/jaekeun.park.7"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "about"
  url = "/about/"
  weight = -180
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -160
